### ISSUE TITLE
[Feature Request] Highlight other matches and repeat with the same char

### ISSUE THREAD

**Issue by kohane27** [TheSafdarAwan/find-extender.nvim#5] opened 2023-04-12 09:23 UTC
Hello there. Hope you're doing well. Thank you for creating `find-extender.nvim`. It makes navigation much more fluent.

```
-- timeout before the find-extender.nvim goes to find apple
   ^
 cursor
```

When I press `ffi`, since there are two matches (i.e, `find` in `find-extender.nvim` and the latter word `find`), the cursor goes to the first one.

Is it possible to highlight other matches and allow users to use the same char to repeat? So in the above case, pressing `ffif` would put the cursor at the word `find`.

Thank you again!

**Comment by theSafdarAwan** [comment] 2023-04-12 09:38
@kohane27 Yes actually i have implemented this feature. But when i was doing that. I realized that code base for this plugin was getting messy because when i was creating this plugin i dint paid attention to code readability and just kept adding new features without doing refactoring.

Now i am half way through refactoring, you can see that in the [refactoring](https://github.com/TheSafdarAwan/find-extender.nvim/tree/refactoring) branch.

This feature has been implemented and it will be added as i merge the `refactoring` branch with main.

Also i have to ask you one thing how would you like represent the next node, i have thought about adding virtual text on top of those next nodes, by giving them alphabets through  `[abcdef]`.

After you search this will highlight the next nodes by giving them a background color different then normal. Then you could pick the assigned alphabet on the target you  want to go to.

Or i could add number from `[1-9]` as virtual text to nodes. Which would be the easier for you.

Or maybe i can add both and user can choose whichever he/she wants to choose.

**Comment by kohane27** [comment] 2023-04-14 09:51
Hello @TheSafdarAwan!

Thank you for getting back to me and doing the refactoring.

I hope it's not too much to ask but I'd recommend seeing how [flit.nvim](https://github.com/ggandor/flit.nvim) and [clever-f.vim](https://github.com/rhysd/clever-f.vim) do the match highlighting. Repeating searches with `fFtT` is quite a common way to navigate between matches.

My workflow is that I use [leap.nvim](https://github.com/ggandor/leap.nvim) to navigate with 2-key search. With `find-extender.nvim` I can search the current line with 2 keys too. Currently the problem is that I can't jump to other duplicate(s).

I look forward to testing out the refactored solution. Thank you again!

**Comment by theSafdarAwan** [comment] 2023-04-14 09:55
> Hello @TheSafdarAwan!
> 
> Thank you for getting back to me and doing the refactoring.
> 
> I hope it's not too much to ask but I'd recommend seeing how [flit.nvim](https://github.com/ggandor/flit.nvim) and [clever-f.vim](https://github.com/rhysd/clever-f.vim) do the match highlighting. Repeating searches with `fFtT` is quite a common way to navigate between matches.
> 
> My workflow is that I use [leap.nvim](https://github.com/ggandor/leap.nvim) to navigate with 2-key search. With `find-extender.nvim` I can search the current line with 2 keys too. Currently the problem is that I can't jump to other duplicate(s).
> 
> I look forward to testing out the refactored solution. Thank you again!

oh that's great, i will do the same, fFtT will be good way.

I will add both type and user can decide which type they want to use.

**Comment by theSafdarAwan** [comment] 2023-04-14 15:17
@kohane27 hey, can you try the `alpha` branch. I didn't push the changes to the `main` branch. 
For a day or two i am going to test the `alpha` branch myself. You can try it out any suggestions are welcome. After that i will merge this to the main branch.

And i implemented you suggestion motion which you said `fFtT`, which wasn't making a lot of sense to me, So instead i created movement called `lh` which lets you move through the matches using `l` and `h` keys.
This seemed to be a good strategy.
Please feel free to give any suggestion.
Thanks!.

**Comment by theSafdarAwan** [comment] 2023-04-16 12:11
@kohane27 Hey, I have tested the `alpha` branch myself and i think it's now good to be merged with the `main` branch.

Have you noticed any issues with it yet.

And by the way thanks for the help 🙏. And you idea to implement the `fFtT` like movement.

**Comment by kohane27** [comment] 2023-04-24 06:26
Hello @TheSafdarAwan, hope you're doing well.

First of all, please accept my apology for taking so long to get back to you. I was occupied with some personal stuff for the past week.

I've tested the `alpha` branch and wow! I couldn't be happier! I couldn't have asked for something better! It's exactly what I hoped to achieve. Thank you so much! Would you be open to setting up github sponsorship so that I can send you some beer or coffee as a token of my gratitude? Also, I've written a blog post about [find-extender.nvim](https://devctrl.blog/posts/find-extender-nvim-like-leap-nvim-but-for-the-current-line/) and hope you like it!

Anyway, please see below for some comments:

## 1. Matching criteria

### First example

To test:

1. On the following line

```
print("find_extender is so precise for finding char in current line.")
^
cursor
```

2. Activate forward search with `ffi` (finding all possible strings containing `fi`)

3. Cursor immediately jumps to `find_extender` as below:

```
print("find_extender is so precise for finding char in current line.")
       ^
    cursor
```

It seems that `find-extender` could not see the second `finding`?

### Second example

1. Given the following:

```
print("find FInd fInd wordfIword WORDFIWORD")
^
cursor
```

2. Activate forward search with `fFI` (finding all possible strings containing `FI`)

3. Cursor immediately jumps to `FInd` and ignoring the second match `WORDFIWORD` (the sandwiched `FI`).

## 2. Allow for `smart_case` and/or `ignore_case`

Given the following testing example:

```
print("find FInd fInd find_extender WORDfiWORD wordfIword WORD_fingWORD")
^
cursor
```

We can verify that all strings containing `fi` is searched (i.e., regardless of their position within the strings). However, `fi` in other alphabetical cases (upper cases or mixed cases) are not searched:

![2023-04-24-14-05-06](https://user-images.githubusercontent.com/57322459/233913965-2bab4fb8-f459-4323-88bb-078d7d52bf04.png)

I understand that it's not a bug, but my suggestion is to allow searching in `smart_case`. For example, [clever-f.vim](https://github.com/rhysd/clever-f.vim#smart-case) has the following config for ignore case and smart case:

> Ignore case
> 
> `g:clever_f_ignore_case` controls whether or not searches are case-insensitive.
>
> Smart case
> 
> `g:clever_f_smart_case` controls whether searches are smart case or not. If you type a lower case character, the case will be ignored. However, if you type an upper case character, it will only search for upper case characters.

I understand that `find-extender` has no obligation to be feature parity with `clever-f` so it's merely a suggestion.

## 3. How to activate `lh` movement instead of `leap`?

Thank you for using `leap` movement as the default. I was trying to test `lh` movement with the following config:

```lua
require("find-extender").setup({
  movments = {
    min_matches = 2,
    highlight_match = { fg = "#c0caf5", bg = "#545c7e" },
    lh = {
      enable = true,
      cursor_hl = { fg = "#545c7e", bg = "#ff9e64" },
    },
    leap = {
      enable = false,
      symbols = "abcdefgh",
    },
  },
})
```

However, `leap` movement is still activated. My guess is that the default config is still loaded and not loading `lh` movement?  I can't seem to disable `leap` and test `lh` movement.

## 4. Allowing users to choose `what pair of chars to activate repeating searches`

Although I don't use `lh` movement, I'd recommend allowing users to choose `what pair of chars to activate repeating searches`. Both [clever-f.vim](https://github.com/rhysd/clever-f.vim) and [flit.nvim](https://github.com/ggandor/flit.nvim) let users to repeat jumping with the same char during searching after typing `f{char}`, `F{char}`, `t{char}` or `T{char}`.

## Conclusion

Thank you once again for bearing with me. Again, please don't feel obliged to look at the above issues. They are just some of my suggestions; whether to fix or implement them are completely up to you. I'm happy and content with the current status of `find_extender`. Thank you and have a good day.

**Comment by TheSafdarAwan** [comment] 2023-04-24 15:02
Thanks for you gratitude i live in Pakistan:pakistan: and github sponsorship isn't available here and to be honest i don't have a credit card or anything. I am learning programming and started writing neovim Plugins to gain some experience on how to code. Thanks for you appreciation, i couldn't be more happier.
And Feature requests are all acceptable because in the end, if someone needed that feature that means it has some significant value to it and i am not [suckless](https://suckless.org/) ideology person. So if you have any other feature in mind please create an issue for it.     

> 1.  Matching criteria
This was a feature that allowed user to not use any of the movements if there are only 2 matches you can disable this by settings this setting
```lua
	movments = {
		---@field min_matches number minimum number of matches required after which
		--- you can use the leap or lh.
		min_matches = 1,
}
```
> 2. Allow for smart_case and/or ignore_case
Well this feature was in my mind, but i was occupied something else that caused me a lot of time loss. There was some bug that i couldn't solve, and after experimenting i finally solved it.
Now i will add this feature tomorrow because i have added somethings that are not added int README. That's why you are getting some unexpected behavior.

> 3. How to activate lh movement instead of leap?
Sorry! there was a typo in source code that's why `lh` movement wasn't getting activated.

> 4. Allowing users to choose what pair of chars to activate repeating searches
Sorry i didn't understand what you said here. I haven't used any of those plugins. So i have no idea what they do please can you elaborate on what are you saying. Thanks‍🔥.

**Comment by TheSafdarAwan** [comment] 2023-04-24 15:17
I have re-opened this issue because all those features need to be added. And in case if you want to start a discussion i have enabled discussions as well.

**Comment by theSafdarAwan** [comment] 2023-04-24 22:33
[ignore case](https://github.com/thesafdarawan/find-extender.nvim/tree/alpha#ignore-case) feature has been added

**Closed as completed** 2023-04-26 00:44 UTC

**Comment by kohane27** [comment] 2023-04-27 07:57
Hello @TheSafdarAwan, hope you're doing well. Below is the follow-up of my previous comment.

## 1. Matching criteria

Apologies that I missed the config. Setting `min_matches = 1` fixed the "1. Matching criteria" "issue" in the previous comment:

```lua
movments = {
    min_matches = 1,
}
```

## 2. lh movement

I've tested the `lh` movement feature and it works as expected! Thank you! Moreover, if you'd like my futher explanations about "Allowing users to choose what pair of chars to activate repeating searches" and suggestions on "lh movement", please see discussion [#6](https://github.com/TheSafdarAwan/find-extender.nvim/discussions/6).
